repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3  # Replace with latest if needed
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: pytest
        name: Run tests with pytest
        entry: poetry run pytest
        language: system
        types: [python]
