default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        name: Ruff Linter
        entry: ruff check
        args: [--fix]
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: local
    hooks:
      - id: pytest
        name: Run tests with pytest
        entry: poetry run pytest organizer/tests
        language: system
        types: [python]
        pass_filenames: false

      - id: commitizen
        name: Commitizen
        description: "Check whether the commit message follows commiting rules"
        entry: cz check
        args: [--allow-abort, --commit-msg-file]
        stages: [commit-msg]
        language: system
